orig=AGC_BLOCK_TWO_SELF_CHECK.s; new=AGC-BLOCK-TWO-SELF--CHECK.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=AGC_BLOCK_TWO_SELF-CHECK.s; new=AGC-BLOCK-TWO-SELF-CHECK.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=AGS_INITIALIZATION.s; new=AGS-INITIALIZATION.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=ALARM_AND_ABORT.s; new=ALARM-AND-ABORT.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=ANGLFIND.s; new=ANGLFIND.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=AOSTASK_AND_AOSJOB.s; new=AOSTASK-AND-AOSJOB.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=AOTMARK.s; new=AOTMARK.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=ASCENT_GUIDANCE.s; new=ASCENT-GUIDANCE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=ASSEMBLY_AND_OPERATION_INFORMATION.s; new=ASSEMBLY-AND-OPERATION-INFORMATION.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=ATTITUDE_MANEUVER_ROUTINE.s; new=ATTITUDE-MANEUVER-ROUTINE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=AUTOMATIC_MANEUVERS.s; new=AUTOMATIC-MANEUVERS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=BURN_BABY_BURN--MASTER_IGNITION_ROUTINE.s; new=BURN-BABY-BURN--MASTER-IGNITION-ROUTINE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=CM_BODY_ATTITUDE.s; new=CM-BODY-ATTITUDE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=CM_ENTRY_DIGITAL_AUTOPILOT.s; new=CM-ENTRY-DIGITAL-AUTOPILOT.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=CONIC_SUBROUTINES.s; new=CONIC-SUBROUTINES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=CONTRACT_AND_APPROVALS.s; new=CONTRACT-AND-APPROVALS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=CONTROLLED_CONSTANTS.s; new=CONTROLLED-CONSTANTS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=CSM_GEOMETRY.s; new=CSM-GEOMETRY.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=DAPIDLER_PROGRAM.s; new=DAPIDLER-PROGRAM.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=DAP_INTERFACE_SUBROUTINES.s; new=DAP-INTERFACE-SUBROUTINES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=DISPLAY_INTERFACE_ROUTINES.s; new=DISPLAY-INTERFACE-ROUTINES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=DOWNLINK_LISTS.s; new=DOWNLINK-LISTS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=DOWN_TELEMETRY_PROGRAM.s; new=DOWN--TELEMETRY-PROGRAM.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=DOWN-TELEMETRY_PROGRAM.s; new=DOWN-TELEMETRY-PROGRAM.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=ENTRY_LEXICON.s; new=ENTRY-LEXICON.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=ERASABLE_ASSIGNMENTS.s; new=ERASABLE-ASSIGNMENTS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=EXECUTIVE.s; new=EXECUTIVE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=EXTENDED_VERBS.s; new=EXTENDED-VERBS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=FINDCDUW--GUIDAP_INTERFACE.s; new=FINDCDUW--GUIDAP-INTERFACE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=FIXED_FIXED_CONSTANT_POOL.s; new=FIXED-FIXED-CONSTANT-POOL.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=FLAGWORD_ASSIGNMENTS.s; new=FLAGWORD-ASSIGNMENTS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=FRESH_START_AND_RESTART.s; new=FRESH-START-AND-RESTART.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=GIMBAL_LOCK_AVOIDANCE.s; new=GIMBAL-LOCK-AVOIDANCE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=GROUND_TRACKING_DETERMINATION_PROGRAM.s; new=GROUND-TRACKING-DETERMINATION-PROGRAM.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=HeaderTemplate.s; new=HeaderTemplate.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=IMU_CALIBRATION_AND_ALIGNMENT.s; new=IMU-CALIBRATION-AND-ALIGNMENT.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=IMU_COMPENSATION_PACKAGE.s; new=IMU-COMPENSATION-PACKAGE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=IMU_MODE_SWITCHING_ROUTINES.s; new=IMU-MODE-SWITCHING-ROUTINES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=IMU_PERFORMANCE_TEST_2.s; new=IMU-PERFORMANCE-TEST-2.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=IMU_PERFORMANCE_TESTS_4.s; new=IMU-PERFORMANCE-TESTS-4.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=INFLIGHT_ALIGNMENT_ROUTINES.s; new=INFLIGHT-ALIGNMENT-ROUTINES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.s; new=INPUT-OUTPUT-CHANNEL-BIT-DESCRIPTIONS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=INTEGRATION_INITIALIZATION.s; new=INTEGRATION-INITIALIZATION.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=INTER-BANK_COMMUNICATION.s; new=INTER-BANK-COMMUNICATION.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=INTERPRETER.s; new=INTERPRETER.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=INTERPRETIVE_CONSTANT.s; new=INTERPRETIVE-CONSTANT.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=INTERPRETIVE_CONSTANTS.s; new=INTERPRETIVE-CONSTANTS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=INTERRUPT_LEAD_INS.s; new=INTERRUPT-LEAD-INS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=JET_SELECTION_LOGIC.s; new=JET-SELECTION-LOGIC.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=KALCMANU_STEERING.s; new=KALCMANU-STEERING.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=KALMAN_FILTER.s; new=KALMAN-FILTER.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=KEYRUPT_UPRUPT.s; new=KEYRUPT-UPRUPT.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=LAMBERT_AIMPOINT_GUIDANCE.s; new=LAMBERT-AIMPOINT-GUIDANCE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=LANDING_ANALOG_DISPLAYS.s; new=LANDING-ANALOG-DISPLAYS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=LATITUDE_LONGITUDE_SUBROUTINES.s; new=LATITUDE-LONGITUDE-SUBROUTINES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=LEM_GEOMETRY.s; new=LEM-GEOMETRY.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=LUNAR_AND_SOLAR_EPHEMERIDES_SUBROUTINES.s; new=LUNAR-AND-SOLAR-EPHEMERIDES-SUBROUTINES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=LUNAR_LANDING_GUIDANCE_EQUATIONS.s; new=LUNAR-LANDING-GUIDANCE-EQUATIONS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=LUNAR_LANDMARK_SELECTION_FOR_CM.s; new=LUNAR-LANDMARK-SELECTION-FOR-CM.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=MAIN.s; new=MAIN.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=MEASUREMENT_INCORPORATION.s; new=MEASUREMENT-INCORPORATION.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=MYSUBS.s; new=MYSUBS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=ORBITAL_INTEGRATION.s; new=ORBITAL-INTEGRATION.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P11.s; new=P11.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P12.s; new=P12.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P20-P25.s; new=P20-P25.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P30_P37.s; new=P30--P37.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P30-P37.s; new=P30-P37.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P32-P33_P72-P73.s; new=P32-P33-P72-P73.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P32-P35_P72-P75.s; new=P32-P35-P72-P75.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P34-35_P74-75.s; new=P34-35-P74-75.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P37_P70.s; new=P37-P70.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P40-P47.s; new=P40-P47.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P51-P53.s; new=P51-P53.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P61-P67.s; new=P61-P67.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P70-P71.s; new=P70-P71.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P76.s; new=P76.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=P-AXIS_RCS_AUTOPILOT.s; new=P-AXIS-RCS-AUTOPILOT.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=PHASE_TABLE_MAINTENANCE.s; new=PHASE-TABLE-MAINTENANCE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=PINBALL_GAME_BUTTONS_AND_LIGHTS.s; new=PINBALL-GAME-BUTTONS-AND-LIGHTS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=PINBALL_NOUN_TABLES.s; new=PINBALL-NOUN-TABLES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=PLANETARY_INERTIAL_ORIENTATION.s; new=PLANETARY-INERTIAL-ORIENTATION.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=POWERED_FLIGHT_SUBROUTINES.s; new=POWERED-FLIGHT-SUBROUTINES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=Q_R-AXIS_RCS_AUTOPILOT.s; new=Q-R-AXIS-RCS-AUTOPILOT.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=R30.s; new=R30.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=R31.s; new=R31.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=R60_62.s; new=R60-62.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=R63.s; new=R63.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=RADAR_LEADIN_ROUTINES.s; new=RADAR-LEADIN-ROUTINES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=RCS-CSM_DAP_EXECUTIVE_PROGRAMS.s; new=RCS-CSM-DAP-EXECUTIVE-PROGRAMS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=RCS-CSM_DIGITAL_AUTOPILOT.s; new=RCS-CSM-DIGITAL-AUTOPILOT.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=RCS_FAILURE_MONITOR.s; new=RCS-FAILURE-MONITOR.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=README.md; new=README.md; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=REENTRY_CONTROL.s; new=REENTRY-CONTROL.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=RESTARTS_ROUTINE.s; new=RESTARTS-ROUTINE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=RESTART_TABLES.s; new=RESTART-TABLES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=RT8_OP_CODES.s; new=RT8-OP-CODES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=RTB_OP_CODES.s; new=RTB-OP-CODES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=S-BAND_ANTENNA_FOR_CM.s; new=S-BAND-ANTENNA-FOR-CM.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=S-BAND_ANTENNA_FOR_LM.s; new=S-BAND-ANTENNA-FOR-LM.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=SERVICER207.s; new=SERVICER207.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=SERVICE_ROUTINES.s; new=SERVICE-ROUTINES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=SERVICER.s; new=SERVICER.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=SINGLE_PRECISION_SUBROUTINES.s; new=SINGLE-PRECISION-SUBROUTINES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=SPS_BACK-UP_RCS_CONTROL.s; new=SPS-BACK-UP-RCS-CONTROL.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=STABLE_ORBIT.s; new=STABLE-ORBIT.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=STAR_TABLES.s; new=STAR-TABLES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=SXTMARK.s; new=SXTMARK.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=SYSTEM_TEST_STANDARD_LEAD_INS.s; new=SYSTEM-TEST-STANDARD-LEAD-INS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=T4RUPT_PROGRAM.s; new=T4RUPT-PROGRAM.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=T6-RUPT_PROGRAMS.s; new=T6-RUPT-PROGRAMS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=TAGS_FOR_RELATIVE_SETLOC.s; new=TAGS-FOR-RELATIVE-SETLOC.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=THE_LUNAR_LANDING.s; new=THE-LUNAR-LANDING.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=THROTTLE_CONTROL_ROUTINES.s; new=THROTTLE-CONTROL-ROUTINES.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=TIME_OF_FREE_FALL.s; new=TIME-OF-FREE-FALL.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=TJET_LAW.s; new=TJET-LAW.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=TPI_SEARCH.s; new=TPI-SEARCH.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=TRIM_GIMBAL_CNTROL_SYSTEM.s; new=TRIM-GIMBAL-CNTROL-SYSTEM.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=TVCDAPS.s; new=TVCDAPS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=TVCEXECUTIVE.s; new=TVCEXECUTIVE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=TVCINITIALIZE.s; new=TVCINITIALIZE.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=TVCMASSPROP.s; new=TVCMASSPROP.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=TVCRESTARTS.s; new=TVCRESTARTS.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=TVCROLLDAP.s; new=TVCROLLDAP.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=TVCSTROKETEST.s; new=TVCSTROKETEST.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=UPDATE_PROGRAM.s; new=UPDATE-PROGRAM.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=WAITLIST.s; new=WAITLIST.s; echo "XX $orig XX"; diff origsrc/$orig src/$new
