#!/bin/bash

orig=Luminary099/AGC_BLOCK_TWO_SELF_CHECK.agc; new=AGC-BLOCK-TWO-SELF-CHECK.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/AGC_BLOCK_TWO_SELF-CHECK.agc; new=AGC-BLOCK-TWO-SELF-CHECK.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/AGS_INITIALIZATION.agc; new=AGS-INITIALIZATION.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/ALARM_AND_ABORT.agc; new=ALARM-AND-ABORT.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/ANGLFIND.agc; new=ANGLFIND.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/AOSTASK_AND_AOSJOB.agc; new=AOSTASK-AND-AOSJOB.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Luminary099/AOTMARK.agc; new=AOTMARK.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Luminary099/ASCENT_GUIDANCE.agc; new=ASCENT-GUIDANCE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/ASSEMBLY_AND_OPERATION_INFORMATION.agc; new=CM0002INFO.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/ATTITUDE_MANEUVER_ROUTINE.agc; new=ATTITUDE-MANEUVER-ROUTINE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/AUTOMATIC_MANEUVERS.agc; new=AUTOMATIC-MANEUVERS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/BURN_BABY_BURN--MASTER_IGNITION_ROUTINE.agc; new=BURN-BABY-BURN--MASTER-IGNITION-ROUTINE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/CM_BODY_ATTITUDE.agc; new=CM-BODY-ATTITUDE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/CM_ENTRY_DIGITAL_AUTOPILOT.agc; new=CM-ENTRY-DIGITAL-AUTOPILOT.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/CONIC_SUBROUTINES.agc; new=CONIC-SUBROUTINES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/CONTRACT_AND_APPROVALS.agc; new=CONTRACT-AND-APPROVALS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/CONTROLLED_CONSTANTS.agc; new=CONTROLLED-CONSTANTS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/CSM_GEOMETRY.agc; new=CSM-GEOMETRY.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/DAPIDLER_PROGRAM.agc; new=DAPIDLER-PROGRAM.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Luminary099/DAP_INTERFACE_SUBROUTINES.agc; new=DAP-INTERFACE-SUBROUTINES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/DISPLAY_INTERFACE_ROUTINES.agc; new=DISPLAY-INTERFACE-ROUTINES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/DOWNLINK_LISTS.agc; new=DOWNLINK-LISTS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/DOWN_TELEMETRY_PROGRAM.agc; new=DOWN--TELEMETRY-PROGRAM.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/DOWN-TELEMETRY_PROGRAM.agc; new=DOWN-TELEMETRY-PROGRAM.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/ENTRY_LEXICON.agc; new=ENTRY-LEXICON.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/ERASABLE_ASSIGNMENTS.agc; new=ERASABLE-ASSIGNMENTS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/EXECUTIVE.agc; new=EXECUTIVE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/EXTENDED_VERBS.agc; new=EXTENDED-VERBS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/FINDCDUW--GUIDAP_INTERFACE.agc; new=FINDCDUW--GUIDAP-INTERFACE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/FIXED_FIXED_CONSTANT_POOL.agc; new=FIXED-FIXED-CONSTANT-POOL.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/FLAGWORD_ASSIGNMENTS.agc; new=FLAGWORD-ASSIGNMENTS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/FRESH_START_AND_RESTART.agc; new=FRESH-START-AND-RESTART.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/GIMBAL_LOCK_AVOIDANCE.agc; new=GIMBAL-LOCK-AVOIDANCE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/GROUND_TRACKING_DETERMINATION_PROGRAM.agc; new=GROUND-TRACKING-DETERMINATION-PROGRAM.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/HeaderTemplate.agc; new=HeaderTemplate.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/IMU_CALIBRATION_AND_ALIGNMENT.agc; new=IMU-CALIBRATION-AND-ALIGNMENT.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/IMU_COMPENSATION_PACKAGE.agc; new=IMU-COMPENSATION-PACKAGE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/IMU_MODE_SWITCHING_ROUTINES.agc; new=IMU-MODE-SWITCHING-ROUTINES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/IMU_PERFORMANCE_TEST_2.agc; new=IMU-PERFORMANCE-TEST-2.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Luminary099/IMU_PERFORMANCE_TESTS_4.agc; new=IMU-PERFORMANCE-TESTS-4.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/INFLIGHT_ALIGNMENT_ROUTINES.agc; new=INFLIGHT-ALIGNMENT-ROUTINES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.agc; new=INPUT-OUTPUT-CHANNEL-BIT-DESCRIPTIONS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/INTEGRATION_INITIALIZATION.agc; new=INTEGRATION-INITIALIZATION.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/INTER-BANK_COMMUNICATION.agc; new=INTER-BANK-COMMUNICATION.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/INTERPRETER.agc; new=INTERPRETER.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/INTERPRETIVE_CONSTANT.agc; new=INTERPRETIVE-CONSTANT.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/INTERPRETIVE_CONSTANTS.agc; new=INTERPRETIVE-CONSTANTS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/INTERRUPT_LEAD_INS.agc; new=INTERRUPT-LEAD-INS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/JET_SELECTION_LOGIC.agc; new=JET-SELECTION-LOGIC.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/KALCMANU_STEERING.agc; new=KALCMANU-STEERING.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/KALMAN_FILTER.agc; new=KALMAN-FILTER.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/KEYRUPT_UPRUPT.agc; new=KEYRUPT-UPRUPT.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/LAMBERT_AIMPOINT_GUIDANCE.agc; new=LAMBERT-AIMPOINT-GUIDANCE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Luminary099/LANDING_ANALOG_DISPLAYS.agc; new=LANDING-ANALOG-DISPLAYS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/LATITUDE_LONGITUDE_SUBROUTINES.agc; new=LATITUDE-LONGITUDE-SUBROUTINES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/LEM_GEOMETRY.agc; new=LEM-GEOMETRY.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/LUNAR_AND_SOLAR_EPHEMERIDES_SUBROUTINES.agc; new=LUNAR-AND-SOLAR-EPHEMERIDES-SUBROUTINES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/LUNAR_LANDING_GUIDANCE_EQUATIONS.agc; new=LUNAR-LANDING-GUIDANCE-EQUATIONS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/LUNAR_LANDMARK_SELECTION_FOR_CM.agc; new=LUNAR-LANDMARK-SELECTION-FOR-CM.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/MAIN.agc; new=MAIN.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/MEASUREMENT_INCORPORATION.agc; new=MEASUREMENT-INCORPORATION.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/MYSUBS.agc; new=MYSUBS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/ORBITAL_INTEGRATION.agc; new=ORBITAL-INTEGRATION.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/P11.agc; new=P11.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/P12.agc; new=P12.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/P20-P25.agc; new=P20-P25.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/P30_P37.agc; new=P30--P37.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/P30-P37.agc; new=P30-P37.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/P32-P33_P72-P73.agc; new=P32-P33-P72-P73.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/P32-P35_P72-P75.agc; new=P32-P35-P72-P75.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/P34-35_P74-75.agc; new=P34-35-P74-75.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/P37_P70.agc; new=P37-P70.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/P40-P47.agc; new=P40-P47.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/P51-P53.agc; new=P51-P53.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/P61-P67.agc; new=P61-P67.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/P70-P71.agc; new=P70-P71.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/P76.agc; new=P76.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/P-AXIS_RCS_AUTOPILOT.agc; new=P-AXIS-RCS-AUTOPILOT.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/PHASE_TABLE_MAINTENANCE.agc; new=PHASE-TABLE-MAINTENANCE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/PINBALL_GAME_BUTTONS_AND_LIGHTS.agc; new=PINBALL-GAME-BUTTONS-AND-LIGHTS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/PINBALL_NOUN_TABLES.agc; new=PINBALL-NOUN-TABLES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/PLANETARY_INERTIAL_ORIENTATION.agc; new=PLANETARY-INERTIAL-ORIENTATION.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/POWERED_FLIGHT_SUBROUTINES.agc; new=POWERED-FLIGHT-SUBROUTINES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/Q_R-AXIS_RCS_AUTOPILOT.agc; new=Q-R-AXIS-RCS-AUTOPILOT.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/R30.agc; new=R30.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/R31.agc; new=R31.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/R60_62.agc; new=R60-62.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/R63.agc; new=R63.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Luminary099/RADAR_LEADIN_ROUTINES.agc; new=RADAR-LEADIN-ROUTINES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/RCS-CSM_DAP_EXECUTIVE_PROGRAMS.agc; new=RCS-CSM-DAP-EXECUTIVE-PROGRAMS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/RCS-CSM_DIGITAL_AUTOPILOT.agc; new=RCS-CSM-DIGITAL-AUTOPILOT.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/RCS_FAILURE_MONITOR.agc; new=RCS-FAILURE-MONITOR.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=README.md; new=README.md; echo "XX $orig XX"; diff origsrc/$orig src/$new
orig=Comanche055/REENTRY_CONTROL.agc; new=REENTRY-CONTROL.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/RESTARTS_ROUTINE.agc; new=RESTARTS-ROUTINE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/RESTART_TABLES.agc; new=RESTART-TABLES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/RT8_OP_CODES.agc; new=RT8-OP-CODES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/RTB_OP_CODES.agc; new=RTB-OP-CODES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/S-BAND_ANTENNA_FOR_CM.agc; new=S-BAND-ANTENNA-FOR-CM.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/S-BAND_ANTENNA_FOR_LM.agc; new=S-BAND-ANTENNA-FOR-LM.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/SERVICER207.agc; new=SERVICER207.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/SERVICE_ROUTINES.agc; new=SERVICE-ROUTINES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/SERVICER.agc; new=SERVICER.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/SINGLE_PRECISION_SUBROUTINES.agc; new=SINGLE-PRECISION-SUBROUTINES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/SPS_BACK-UP_RCS_CONTROL.agc; new=SPS-BACK-UP-RCS-CONTROL.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/STABLE_ORBIT.agc; new=STABLE-ORBIT.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/STAR_TABLES.agc; new=STAR-TABLES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/SXTMARK.agc; new=SXTMARK.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/SYSTEM_TEST_STANDARD_LEAD_INS.agc; new=SYSTEM-TEST-STANDARD-LEAD-INS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/T4RUPT_PROGRAM.agc; new=T4RUPT-PROGRAM.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/T6-RUPT_PROGRAMS.agc; new=T6-RUPT-PROGRAMS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/TAGS_FOR_RELATIVE_SETLOC.agc; new=TAGS-FOR-RELATIVE-SETLOC.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/THE_LUNAR_LANDING.agc; new=THE-LUNAR-LANDING.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Luminary099/THROTTLE_CONTROL_ROUTINES.agc; new=THROTTLE-CONTROL-ROUTINES.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/TIME_OF_FREE_FALL.agc; new=TIME-OF-FREE-FALL.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/TJET_LAW.agc; new=TJET-LAW.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/TPI_SEARCH.agc; new=TPI-SEARCH.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Luminary099/TRIM_GIMBAL_CNTROL_SYSTEM.agc; new=TRIM-GIMBAL-CNTROL-SYSTEM.agc; echo "XX $orig XX"; diff origsrc/$orig src/Luminary099/$new
orig=Comanche055/TVCDAPS.agc; new=TVCDAPS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/TVCEXECUTIVE.agc; new=TVCEXECUTIVE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/TVCINITIALIZE.agc; new=TVCINITIALIZE.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/TVCMASSPROP.agc; new=TVCMASSPROP.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/TVCRESTARTS.agc; new=TVCRESTARTS.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/TVCROLLDAP.agc; new=TVCROLLDAP.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/TVCSTROKETEST.agc; new=TVCSTROKETEST.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/UPDATE_PROGRAM.agc; new=UPDATE-PROGRAM.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
orig=Comanche055/WAITLIST.agc; new=WAITLIST.agc; echo "XX $orig XX"; diff origsrc/$orig src/Comanche055/$new
